@baseUrl = http://localhost:8090/api/v1

###

GET {{baseUrl}}/docs

###

GET {{baseUrl}}/pages?err=hello

###

GET {{baseUrl}}/raw-response

###
POST {{baseUrl}}/users/login
Content-Type: application/json

{
    "username": "admin",
    "password": "admin"
}

###

POST {{baseUrl}}/users
Content-Type: application/json

{}

###

GET {{baseUrl}}/blobs/download/abc
Authorization: admin

###

POST {{baseUrl}}/blobs/upload
Authorization: admin
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="name"

A sample file
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"; filename="sample.txt"
Content-Type: text/plain

< ./api.http
------WebKitFormBoundary7MA4YWxkTrZu0gW--