@baseUrl = http://localhost:8090/api/v1

###

POST {{baseUrl}}/products?limit=102&test=a&test=b&t=1&t=5&t=500

{
    "photos": [{}]
}

###

GET {{baseUrl}}/products/123Hello


###

GET {{baseUrl}}/view-pdf

###

POST {{baseUrl}}/calc/123/add

{
    "a": 5,
    "b": 2
}

###

GET {{baseUrl}}/standard-handler
Authorization: abc


###

GET {{baseUrl}}/abc/err

###

POST {{baseUrl}}/calc/y/another/.custom./routed/000


###

GET http://localhost:8090/abcsd/asdad
